//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetYazılım22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class araclar
    {
        public int id { get; set; }
        public int musteri_id { get; set; }
        public string plaka { get; set; }
        public string saseno { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public Nullable<int> yil { get; set; }
        public string motor_hacmi { get; set; }
        public string yakit_turu { get; set; }
        public string vites_turu { get; set; }
        public string kasa_tipi { get; set; }
        public string renk { get; set; }
        public Nullable<int> km { get; set; }
        public string sigorta_durumu { get; set; }
        public Nullable<System.DateTime> sigorta_bitis_tarihi { get; set; }
        public Nullable<System.DateTime> muayene_bitis_tarihi { get; set; }
        public string ruhsat_sahibi { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> eklenme_tarihi { get; set; }
    }
}
