//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetYazılım22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class faturalar
    {
        public int id { get; set; }
        public int servis_id { get; set; }
        public int musteri_id { get; set; }
        public Nullable<decimal> toplam_tutar { get; set; }
        public Nullable<System.DateTime> fatura_tarihi { get; set; }
        public string odeme_durumu { get; set; }
    }
}
