//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetYazılım22.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtoServisDBEntities : DbContext
    {
        public OtoServisDBEntities()
            : base("name=OtoServisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<araclar> araclars { get; set; }
        public virtual DbSet<faturalar> faturalars { get; set; }
        public virtual DbSet<kullanici> kullanicis { get; set; }
        public virtual DbSet<musteriler> musterilers { get; set; }
        public virtual DbSet<personel> personels { get; set; }
        public virtual DbSet<personel_gunluk_aktiviteler> personel_gunluk_aktiviteler { get; set; }
        public virtual DbSet<personel_maas_odeme> personel_maas_odeme { get; set; }
        public virtual DbSet<servis_kayitlari> servis_kayitlari { get; set; }
        public virtual DbSet<servis_parcalari> servis_parcalari { get; set; }
        public virtual DbSet<sms_eposta_kayitlari> sms_eposta_kayitlari { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<yedek_parcalar> yedek_parcalar { get; set; }
    }
}
