//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetYazılım22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_gunluk_aktiviteler
    {
        public int id { get; set; }
        public int personel_id { get; set; }
        public Nullable<int> servis_id { get; set; }
        public Nullable<int> arac_id { get; set; }
        public System.DateTime tarih { get; set; }
        public System.TimeSpan baslangic_saati { get; set; }
        public System.TimeSpan bitis_saati { get; set; }
        public string yapilan_islem { get; set; }
        public string is_durumu { get; set; }
    }
}
