//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetYazılım22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servis_kayitlari
    {
        public int id { get; set; }
        public int arac_id { get; set; }
        public int musteri_id { get; set; }
        public Nullable<System.DateTime> servis_tarihi { get; set; }
        public string servis_durumu { get; set; }
        public Nullable<decimal> toplam_ucret { get; set; }
        public string aciklama { get; set; }
    }
}
