//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetYazılım22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_eposta_kayitlari
    {
        public int id { get; set; }
        public int musteri_id { get; set; }
        public string mesaj_tipi { get; set; }
        public string icerik { get; set; }
        public Nullable<System.DateTime> gonderim_tarihi { get; set; }
    }
}
