//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetYazılım22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yedek_parcalar
    {
        public int id { get; set; }
        public string parca_adi { get; set; }
        public string parca_kodu { get; set; }
        public string marka { get; set; }
        public Nullable<int> stok_miktari { get; set; }
        public Nullable<decimal> birim_fiyat { get; set; }
        public string tedarikci { get; set; }
        public Nullable<System.DateTime> eklenme_tarihi { get; set; }
    }
}
